const defaults={income:10700,fixed:6180,saving:1120};
const defaultBudgets=[{name:'Lebensmittel',limit:900},{name:'Shopping',limit:500},{name:'Transport',limit:450},{name:'Freizeit',limit:350},{name:'Abonnements',limit:180}];
let settings=JSON.parse(localStorage.getItem('bq_settings')||'null')||defaults;
let budgets=JSON.parse(localStorage.getItem('bq_budgets')||'null')||defaultBudgets;
let tx=JSON.parse(localStorage.getItem('bq_tx')||'[]');
let xp=Number(localStorage.getItem('bq_xp')||2480),csvRows=[],undoItem=null,undoTimer=null;
budgets=budgets.map(b=>({name:b.name,limit:+b.limit||0}));
const $=id=>document.getElementById(id);
const money=v=>'CHF '+Number(v||0).toLocaleString('de-CH',{minimumFractionDigits:0,maximumFractionDigits:2});
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const parseDate=v=>{const d=new Date(v);return isNaN(d)?null:d};
const monthTx=(month=new Date().getMonth(),year=new Date().getFullYear())=>tx.filter(t=>{const d=parseDate(t.date);return d&&d.getMonth()===month&&d.getFullYear()===year});
const monthSpent=(month,year)=>monthTx(month,year).reduce((s,t)=>s+Math.abs(+t.amount||0),0);
function saveAll(){localStorage.setItem('bq_settings',JSON.stringify(settings));localStorage.setItem('bq_budgets',JSON.stringify(budgets));localStorage.setItem('bq_tx',JSON.stringify(tx));localStorage.setItem('bq_xp',xp)}
function categorySpent(name){return monthTx().filter(t=>t.cat===name).reduce((s,t)=>s+Math.abs(+t.amount||0),0)}
function savingRate(){const spent=monthSpent(new Date().getMonth(),new Date().getFullYear())+Number(settings.fixed||0);return settings.income?Math.max(-100,Math.round((settings.income-spent)/settings.income*100)):0}
function score(){const totalBudget=budgets.reduce((s,b)=>s+b.limit,0),variable=monthSpent(new Date().getMonth(),new Date().getFullYear()),budgetScore=totalBudget?Math.max(0,1-variable/totalBudget):1,rate=Math.max(0,savingRate())/40;return Math.max(0,Math.min(100,Math.round(55+budgetScore*25+Math.min(1,rate)*20)))}
function render(){const now=new Date(),m=now.getMonth(),y=now.getFullYear(),variable=monthSpent(m,y),available=settings.income-settings.fixed-variable,totalOut=settings.fixed+variable,rate=savingRate(),financialScore=score();
$('incomeHero').textContent=money(available);$('heroSpent').textContent=`${money(totalOut)} Ausgaben diesen Monat`;$('scoreRing').style.setProperty('--p',financialScore);$('scoreValue').textContent=financialScore;$('incomeMetric').textContent=money(settings.income);$('expenseMetric').textContent=money(totalOut);$('savingRateMetric').textContent=rate+' %';$('levelBadge').textContent=`Level ${Math.floor(xp/400)+1} · ${xp.toLocaleString('de-CH')} XP`;
$('incomeInput').value=settings.income;$('fixedInput').value=settings.fixed;$('savingInput').value=settings.saving;$('goalValue').textContent=money(settings.saving);$('budgetList').innerHTML=budgets.map(b=>budgetCard(b,false)).join('');$('budgetList2').innerHTML=budgets.map((b,i)=>budgetCard(b,true,i)).join('');
$('txCategory').innerHTML=$('receiptCategory').innerHTML=budgets.map(b=>`<option>${esc(b.name)}</option>`).join('');$('txDate').value=new Date().toISOString().slice(0,10);renderTransactions();renderChart();renderInsights();fillYears();renderStats()}
function budgetCard(b,edit,i){const spent=categorySpent(b.name),p=b.limit?Math.min(100,spent/b.limit*100):0;return`<div class="budget-item"><div class="metric-line"><strong>${esc(b.name)}</strong><span>${money(spent)} / ${money(b.limit)}</span></div><div class="progress"><span style="width:${p}%"></span></div>${edit?`<div class="actions" style="margin-top:10px"><button class="btn secondary" onclick="editBudget(${i})">Bearbeiten</button><button class="btn danger" onclick="deleteBudget(${i})">Löschen</button></div>`:''}</div>`}
function renderTransactions(){const sorted=tx.map((t,i)=>({...t,_i:i})).sort((a,b)=>(parseDate(b.date)||0)-(parseDate(a.date)||0));$('transactionsList').innerHTML=sorted.length?sorted.map(t=>`<div class="transaction-shell" data-index="${t._i}"><div class="delete-bg">Löschen</div><div class="transaction"><div><div class="tx-title">${esc(t.title)}</div><div class="tx-meta">${esc(t.cat||'Nicht zugeordnet')} · ${esc(t.date||'')}</div></div><strong class="negative">-${money(Math.abs(t.amount))}</strong></div></div>`).join(''):'<div class="empty">Noch keine Buchungen.</div>';bindSwipe()}
function bindSwipe(){document.querySelectorAll('.transaction-shell').forEach(shell=>{const row=shell.querySelector('.transaction');let start=0,delta=0,active=false;row.addEventListener('pointerdown',e=>{start=e.clientX;active=true;row.setPointerCapture(e.pointerId);row.classList.add('dragging')});row.addEventListener('pointermove',e=>{if(!active)return;delta=Math.min(0,Math.max(-120,e.clientX-start));row.style.transform=`translateX(${delta}px)`});const finish=()=>{if(!active)return;active=false;row.classList.remove('dragging');if(delta<-72){row.style.transform='translateX(-120px)';setTimeout(()=>removeTransaction(Number(shell.dataset.index)),120)}else row.style.transform='translateX(0)';delta=0};row.addEventListener('pointerup',finish);row.addEventListener('pointercancel',finish)})}
function removeTransaction(index){undoItem={item:tx[index],index};tx.splice(index,1);saveAll();render();showUndo()}
function showUndo(){clearTimeout(undoTimer);$('toast').classList.add('show');undoTimer=setTimeout(()=>{$('toast').classList.remove('show');undoItem=null},5000)}
$('undoBtn').addEventListener('click',()=>{if(!undoItem)return;tx.splice(undoItem.index,0,undoItem.item);undoItem=null;clearTimeout(undoTimer);$('toast').classList.remove('show');saveAll();render()});
function renderChart(){const now=new Date(),vals=[];for(let i=5;i>=0;i--){const d=new Date(now.getFullYear(),now.getMonth()-i,1),expenses=monthSpent(d.getMonth(),d.getFullYear())+Number(settings.fixed||0);vals.push({label:d.toLocaleDateString('de-CH',{month:'short'}),income:Number(settings.income||0),expenses})}const max=Math.max(1,...vals.flatMap(v=>[v.income,v.expenses]));$('monthChart').innerHTML=vals.map(v=>`<div class="month-bar"><div class="bar-pair"><div class="bar income" style="height:${v.income/max*100}%" title="Einnahmen ${money(v.income)}"></div><div class="bar expense" style="height:${v.expenses/max*100}%" title="Ausgaben ${money(v.expenses)}"></div></div><span class="month-label">${v.label}</span></div>`).join('')}
function renderInsights(){const current=monthSpent(new Date().getMonth(),new Date().getFullYear()),prevDate=new Date(new Date().getFullYear(),new Date().getMonth()-1,1),prev=monthSpent(prevDate.getMonth(),prevDate.getFullYear()),diff=prev?Math.round((current-prev)/prev*100):0,top=budgets.map(b=>({name:b.name,value:categorySpent(b.name)})).sort((a,b)=>b.value-a.value)[0];$('insights').innerHTML=`<div class="insight"><strong>${diff<=0?'📉 Gute Entwicklung':'📈 Ausgaben gestiegen'}</strong><div class="tiny">${prev?`${Math.abs(diff)} % ${diff<=0?'weniger':'mehr'} variable Ausgaben als im Vormonat.`:'Noch kein Vormonatsvergleich verfügbar.'}</div></div><div class="insight"><strong>🎯 Sparquote ${savingRate()} %</strong><div class="tiny">${savingRate()>=20?'Du liegst über einer starken Sparquote von 20 %.':'Das nächste Etappenziel sind 20 % Sparquote.'}</div></div><div class="insight"><strong>🛒 Top-Kategorie: ${esc(top?.name||'–')}</strong><div class="tiny">${money(top?.value||0)} im aktuellen Monat.</div></div>`}
function saveSettings(e){e.preventDefault();settings={income:+$('incomeInput').value,fixed:+$('fixedInput').value,saving:+$('savingInput').value};saveAll();render()}
function addBudget(e){e.preventDefault();budgets.push({name:$('newCat').value.trim(),limit:+$('newLimit').value});e.target.reset();saveAll();render()}
function editBudget(i){const n=prompt('Kategoriename',budgets[i].name),l=n===null?null:prompt('Monatslimit',budgets[i].limit);if(n!==null&&l!==null&&!isNaN(+l)){budgets[i]={name:n.trim()||budgets[i].name,limit:Math.max(0,+l)};saveAll();render()}}
function deleteBudget(i){if(confirm('Kategorie löschen?')){budgets.splice(i,1);saveAll();render()}}
function addTransaction(e){e.preventDefault();tx.push({title:$('txTitle').value.trim(),amount:+$('txAmount').value,cat:$('txCategory').value,date:$('txDate').value});xp+=20;e.target.reset();$('txDialog').close();saveAll();render()}
function fillYears(){const years=new Set([new Date().getFullYear()]);tx.forEach(t=>{const d=parseDate(t.date);if(d)years.add(d.getFullYear())});const selected=+$('yearSelect').value||new Date().getFullYear();$('yearSelect').innerHTML=[...years].sort((a,b)=>b-a).map(y=>`<option ${selected===y?'selected':''}>${y}</option>`).join('')}
function renderStats(){if(!$('yearSelect').options.length)return;const year=+$('yearSelect').value,months=Array(12).fill(0);tx.forEach(t=>{const d=parseDate(t.date);if(d&&d.getFullYear()===year)months[d.getMonth()]+=Math.abs(+t.amount||0)});const total=months.reduce((a,b)=>a+b,0),active=months.filter(Boolean),avg=active.length?total/active.length:0,min=active.length?Math.min(...active):0,names=['Jan','Feb','Mär','Apr','Mai','Jun','Jul','Aug','Sep','Okt','Nov','Dez'];$('yearExpense').textContent=money(total);$('monthAverage').textContent=money(avg);$('bestMonth').textContent=active.length?names[months.indexOf(min)]:'–';$('yearChart').innerHTML=months.map((v,i)=>`<div class="month-bar"><div class="bar-pair"><div class="bar expense" style="height:${Math.max(2,v/Math.max(...months,1)*100)}%"></div></div><span class="month-label">${names[i]}</span></div>`).join('')}
function guessCategory(name){return /(migros|coop|denner|aldi|lidl|volg|spar)/i.test(name)?'Lebensmittel':/(shell|esso|avia|bp|agrola)/i.test(name)?'Transport':/(ikea|jumbo|manor|zara|h&m|galaxus|digitec)/i.test(name)?'Shopping':budgets[0]?.name||''}
function parseAmount(s){return Number(String(s).replace(/'/g,'').replace(',','.').replace(/[^0-9.]/g,''))}
function prepareImage(file){return new Promise((resolve,reject)=>{const img=new Image(),url=URL.createObjectURL(file);img.onload=()=>{const scale=Math.min(1,900/img.width),w=Math.round(img.width*scale),h=Math.round(img.height*scale),c=document.createElement('canvas');c.width=w;c.height=h;const ctx=c.getContext('2d');ctx.drawImage(img,0,0,w,h);URL.revokeObjectURL(url);resolve(c)};img.onerror=reject;img.src=url})}
function extractFast(text){const lines=text.split(/\r?\n/).map(x=>x.trim()).filter(Boolean),known=['Migros','Coop','Denner','Aldi','Lidl','Volg','Spar','Jumbo','IKEA','Digitec','Galaxus','Manor'];let merchant=known.find(k=>new RegExp(k,'i').test(text))||lines.find(x=>/[A-Za-zÄÖÜäöü]{3}/.test(x)&&!/(quittung|kassenbon|beleg|total|summe|mwst)/i.test(x))||'Beleg';let totals=[];lines.filter(l=>/total|summe|betrag|zu zahlen|endbetrag/i.test(l)).forEach(l=>(l.match(/\d{1,5}[.,]\d{2}/g)||[]).forEach(n=>totals.push(parseAmount(n))));if(!totals.length)(text.match(/\d{1,5}[.,]\d{2}/g)||[]).slice(-8).forEach(n=>totals.push(parseAmount(n)));return{merchant,amount:Math.max(...totals.filter(Number.isFinite),0),cat:guessCategory(merchant)}}
async function scanReceipt(file){if(!file)return;$('receiptPreview').src=URL.createObjectURL(file);$('receiptPreview').hidden=false;$('receiptForm').hidden=true;$('receiptStatus').textContent='Beleg wird vorbereitet…';try{const canvas=await prepareImage(file);$('receiptStatus').textContent='Laden und Total werden erkannt…';const result=await Tesseract.recognize(canvas,'deu');const d=extractFast(result.data.text);$('receiptMerchant').value=d.merchant;$('receiptAmount').value=d.amount||'';$('receiptCategory').value=budgets.some(b=>b.name===d.cat)?d.cat:(budgets[0]?.name||'');$('receiptForm').hidden=false;$('receiptStatus').textContent=d.amount?'Fertig – bitte kurz prüfen.':'Total bitte manuell ergänzen.'}catch(e){$('receiptStatus').textContent='Scan fehlgeschlagen: '+e.message}}
function saveReceipt(e){e.preventDefault();tx.push({title:$('receiptMerchant').value.trim(),amount:+$('receiptAmount').value,cat:$('receiptCategory').value,date:new Date().toISOString().slice(0,10),source:'receipt'});xp+=25;saveAll();render();$('receiptDialog').close();e.target.reset();$('receiptPreview').hidden=true}
function readCsv(file){if(!file)return;const r=new FileReader();r.onload=()=>{$('csvStatus').textContent='CSV geladen. Import ist in dieser Version vorbereitet.';$('importCsvBtn').disabled=false;csvRows=[r.result]};r.readAsText(file)}
function importCsv(){$('csvStatus').textContent='CSV-Import bleibt kompatibel und wird im nächsten Schritt erweitert.'}
document.querySelectorAll('.nav button').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.nav button').forEach(b=>b.classList.remove('active'));document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));btn.classList.add('active');$(btn.dataset.target).classList.add('active');scrollTo({top:0,behavior:'smooth'})}));
if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js');render();